name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: npm
      
      - env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm test
          npm version ${TAG_NAME} --git-tag-version=false
          npm whoami; npm --ignore-scripts publish
